### ISSUE TITLE
不过盾配置，容器将无法启动

### ISSUE THREAD

**Issue by kotlef** [lyy0709/cockroachai-oauth#3]
选择不过盾配置安装
docker-compose.yml

```
services:
  ja3-proxy:
    image: xyhelper/ja3-proxy:latest
    ports:
      - "19966:9988" # JA3端口
    environment:
      WEBSITE_URL: "https://chat.openai.com/"
      PROXY: ""  
      CLIENTKEY: "" 
      LOCALPROXYUSER: "bxj58bwc" 
      LOCALPROXYPASS: "dg8ypr75b6km" 
```

ja3容器无法启动，自动关闭

```
root-ja3-proxy-1  | 2024-04-28 15:53:42.582 [INFO] {6dada0a16b62ca1765cbd66268746b01} WEBSITE_URL: https://chat.openai.com/
root-ja3-proxy-1  | 2024-04-28 15:53:42.583 [INFO] {6dada0a16b62ca1765cbd66268746b01} PROXY:
root-ja3-proxy-1  | 2024-04-28 15:53:42.583 [INFO] {6dada0a16b62ca1765cbd66268746b01} LOCALPROXYUSER: bxj58bwc
root-ja3-proxy-1  | 2024-04-28 15:53:42.642 [WARN] {6dada0a16b62ca1765cbd66268746b01} CLIENTKEY is empty,will not use it
root-ja3-proxy-1  | 2024/04/28 15:53:42 Starting http proxy server on http://bxj58bwc:dg8ypr75b6km@:3128
root-ja3-proxy-1  | 2024-04-28 15:53:52.643 [INFO] {6a6256a56b62ca1766cbd6625562fa4b} CheckCFNeed https://chat.openai.com/
root-ja3-proxy-1  | 2024-04-28 15:53:52.689 [WARN] {6a6256a56b62ca1766cbd6625562fa4b} 403 need cf bypass
root-ja3-proxy-1  | 2024-04-28 15:53:52.690 [ERRO] {6a6256a56b62ca1766cbd6625562fa4b} ClientKey is empty,please set it,get it from https://yescaptcha.com/i/RLazNv 
root-ja3-proxy-1  | Stack:
root-ja3-proxy-1  | 1.  main.main
root-ja3-proxy-1  |     /root/xydev/xyhelper-ja3-proxy/main.go:36
root-ja3-proxy-1  | 
```
